### ISSUE TITLE
Disabled people 

### ISSUE THREAD

**Issue by msbegee** [microsoft/vscode-copilot-release#1417]
- Copilot Chat Extension Version:
- VS Code Version:
- OS Version:
- Logs:

Steps to Reproduce:

1.
2.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-copilot-release/issues/1416
- [ ] https://github.com/microsoft/vscode-copilot-release/issues/1410
- [ ] https://github.com/microsoft/vscode-copilot-release/issues/1415
```
